'use client';

import { useState } from 'react';

const faqs = [
  {
    question: 'Is it really invisible to Zoom, Meet, Teams, and Chrome screen share?',
    answer: 'Yes. ZoomGuru uses OS-level window exclusion APIs: SetWindowDisplayAffinity on Windows and setContentProtection on macOS. These are the same APIs used by DRM software to block screen capture. They operate below the application layer, so Zoom, Google Meet, Microsoft Teams, Webex, and browser-based screen sharing cannot capture the overlay. Your interviewer sees only your camera feed.',
  },
  {
    question: 'Is my CV data safe?',
    answer: 'Your CV text is sent over HTTPS and stored encrypted in our database, used only to personalise your AI prompts. We never sell, share, or use it for any other purpose. You can delete your CV and all account data at any time from Settings inside the app.',
  },
  {
    question: 'Does it work offline?',
    answer: 'ZoomGuru requires an internet connection for AI responses. Answers are generated by DeepSeek models running on our servers. However, local wake word detection and speech transcription via the Whisper tiny model run entirely on device and work offline.',
  },
  {
    question: 'Can I use it on multiple devices?',
    answer: 'Each license is device-locked to one machine using a SHA-256 hardware fingerprint. One license equals one machine. If you get a new device, contact support and we will transfer it, up to once per 90 days.',
  },
  {
    question: 'What do I get on the free plan?',
    answer: 'The free plan gives you 3 complete interview sessions and up to 10 AI responses per session. No credit card required. Just download, create an account, and start.',
  },
  {
    question: 'How fast are the answers?',
    answer: 'The first word appears in under 500ms from when you trigger a request. Full answers stream word by word over 2 to 4 seconds so you can start reading and speaking almost immediately.',
  },
];

function FAQItem({ faq, isOpen, onToggle }: { faq: (typeof faqs)[0]; isOpen: boolean; onToggle: () => void }) {
  return (
    <div
      className="rounded-2xl overflow-hidden transition-all duration-200"
      style={{
        background: isOpen ? 'rgba(255,255,255,0.07)' : 'rgba(255,255,255,0.03)',
        border: `1px solid ${isOpen ? 'rgba(255,255,255,0.15)' : 'rgba(255,255,255,0.07)'}`,
      }}
    >
      <button onClick={onToggle} className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left">
        <span className={`font-semibold text-sm leading-snug ${isOpen ? 'text-white' : 'text-white/70'}`}>
          {faq.question}
        </span>
        <span
          className={`flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center transition-all duration-200 ${isOpen ? 'bg-white text-black rotate-45' : 'text-white/50'}`}
          style={isOpen ? {} : { border: '1px solid rgba(255,255,255,0.15)' }}
        >
          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
          </svg>
        </span>
      </button>
      {isOpen && (
        <div className="px-6 pb-5">
          <p className="text-white/65 text-sm leading-relaxed font-light">{faq.answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section id="faq" className="py-28 px-4 relative overflow-hidden">
      <div className="max-w-3xl mx-auto relative z-10">

        <div className="text-center mb-14">
          <p className="text-white/65 text-xs font-bold uppercase tracking-[0.2em] mb-4">FAQ</p>
          <h2 className="text-4xl sm:text-5xl font-black text-white mb-5 tracking-tight">Common questions</h2>
          <p className="text-white/65 text-lg font-light">
            Anything else?{' '}
            <a href="mailto:support@zoomguru.com" className="text-white/80 hover:text-white transition-colors underline underline-offset-2">
              Email us
            </a>
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <FAQItem key={i} faq={faq} isOpen={openIndex === i} onToggle={() => setOpenIndex(openIndex === i ? null : i)} />
          ))}
        </div>

        <div
          className="mt-14 text-center rounded-2xl p-10"
          style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)' }}
        >
          <h3 className="text-white font-black text-2xl mb-3 tracking-tight">
            Ready to ace your next interview?
          </h3>
          <p className="text-white/65 text-sm mb-8 font-light">
            Start free with no card required. 3 full sessions to see if ZoomGuru changes the game for you.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a href="/pricing" className="btn-shimmer font-bold py-3.5 px-8 rounded-xl transition-all duration-200 hover:scale-[1.02]">
              Start free
            </a>
            <a
              href="/download"
              className="text-white/65 hover:text-white font-semibold py-3.5 px-8 rounded-xl transition-all duration-200 inline-flex items-center justify-center gap-2"
              style={{ border: '1px solid rgba(255,255,255,0.12)' }}
            >
              Download now
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
