'use client';

import { useState } from 'react';

const faqs = [
  {
    question: 'Is it really invisible to Zoom, Meet, and Teams?',
    answer:
      'Yes — ZoomGuru uses OS-level window exclusion APIs: SetWindowDisplayAffinity on Windows and CGWindowListCreateImage exclusion on macOS. These are the same APIs used by password managers and DRM-protected apps to prevent screen capture. Zoom, Google Meet, Microsoft Teams, and Webex cannot capture the overlay. Your interviewer sees only your camera feed.',
  },
  {
    question: 'Is my CV data safe?',
    answer:
      'Your CV text is uploaded over HTTPS and stored encrypted in our database server-side. It is only used to personalise your AI prompts — we never sell, share, or use it for any other purpose. You can delete your CV and account data at any time from the app Settings.',
  },
  {
    question: 'Does it work offline?',
    answer:
      'ZoomGuru requires an internet connection for AI responses — answers are generated by DeepSeek models running on our servers. However, the local wake word detection ("Hey ZoomGuru") and microphone transcription (Whisper tiny model) run entirely on-device and work offline. You just won\'t be able to generate AI answers without a connection.',
  },
  {
    question: 'Can I use it on multiple devices?',
    answer:
      'Each license is device-locked to one machine using a SHA-256 hardware fingerprint. One license = one machine. If you need to transfer your license to a new device (e.g., you bought a new laptop), contact support@zoomguru.com and we\'ll transfer it for you — up to once per 90 days.',
  },
  {
    question: 'What if I\'m on the free trial?',
    answer:
      'The free plan gives you 3 complete interview sessions and up to 10 AI responses per session. No credit card required — just download and log in. Screenshot mode and wake word detection are not available on the free plan, but you get the core audio-to-answer experience to evaluate whether ZoomGuru works for you.',
  },
  {
    question: 'How fast are the answers?',
    answer:
      'The first word appears in under 500ms from when you trigger a request. Full answers typically arrive in 2-4 seconds, streamed word by word — so you can start reading and speaking almost immediately. Coding and system design questions routed to DeepSeek R1 (reasoning mode) may take slightly longer as the model thinks through the problem step by step.',
  },
];

function FAQItem({
  faq,
  isOpen,
  onToggle,
}: {
  faq: (typeof faqs)[0];
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div
      className={`border rounded-xl overflow-hidden transition-all duration-200 ${
        isOpen ? 'border-blue-600/40 bg-zinc-900' : 'border-zinc-800 bg-zinc-900/50'
      }`}
    >
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left hover:bg-zinc-800/30 transition-colors"
      >
        <span
          className={`font-semibold text-base ${isOpen ? 'text-white' : 'text-zinc-200'}`}
        >
          {faq.question}
        </span>
        <span
          className={`flex-shrink-0 w-6 h-6 rounded-full border flex items-center justify-center transition-all duration-200 ${
            isOpen
              ? 'border-blue-500 bg-blue-600 text-white rotate-45'
              : 'border-zinc-700 text-zinc-400'
          }`}
        >
          <svg
            className="w-3 h-3"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2.5}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
          </svg>
        </span>
      </button>

      {isOpen && (
        <div className="px-6 pb-5">
          <p className="text-zinc-400 text-sm leading-relaxed">{faq.answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section
      id="faq"
      className="py-24 px-4 bg-zinc-950 relative overflow-hidden"
    >
      <div className="absolute top-1/2 right-0 w-[400px] h-[400px] bg-blue-600/5 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-3xl mx-auto relative z-10">
        {/* Header */}
        <div className="text-center mb-12">
          <p className="text-blue-400 text-sm font-semibold uppercase tracking-widest mb-3">
            FAQ
          </p>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Common questions
          </h2>
          <p className="text-zinc-400 text-lg">
            Anything else? Email us at{' '}
            <a
              href="mailto:support@zoomguru.com"
              className="text-blue-400 hover:underline"
            >
              support@zoomguru.com
            </a>
          </p>
        </div>

        {/* FAQ list */}
        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <FAQItem
              key={i}
              faq={faq}
              isOpen={openIndex === i}
              onToggle={() => setOpenIndex(openIndex === i ? null : i)}
            />
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="mt-12 text-center bg-gradient-to-br from-blue-600/10 to-violet-600/10 border border-blue-600/20 rounded-2xl p-8">
          <h3 className="text-white font-bold text-xl mb-2">
            Ready to ace your next interview?
          </h3>
          <p className="text-zinc-400 text-sm mb-6">
            Start free — no card required. 3 sessions to see if ZoomGuru
            changes the game for you.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a
              href="#pricing"
              className="bg-blue-600 hover:bg-blue-500 text-white font-semibold py-3 px-8 rounded-xl transition-all duration-200 hover:scale-[1.02]"
            >
              Start Free — 3 Sessions
            </a>
            <a
              href="/download"
              className="border border-zinc-700 hover:border-zinc-500 text-zinc-300 hover:text-white font-semibold py-3 px-8 rounded-xl transition-all duration-200"
            >
              Download Now
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
