'use client';

import { useState } from 'react';

const faqs = [
  // Product
  {
    category: 'Product',
    question: 'Is it really invisible to Zoom, Meet, Teams, and Chrome screen share?',
    answer: 'Yes. ZoomGuru uses OS-level window exclusion APIs: SetWindowDisplayAffinity (WDA_EXCLUDEFROMCAPTURE) on Windows and setContentProtection on macOS. These are the same APIs used by DRM software to block screen capture. They operate below the application layer, so Zoom, Google Meet, Microsoft Teams, Webex, OBS, and browser-based screen sharing cannot capture the overlay. Every time the app launches it runs a silent self-test and shows a green "Hidden" badge in the header to confirm protection is active.',
  },
  {
    category: 'Product',
    question: 'How fast are the answers?',
    answer: 'The first word appears in under 500ms from when you trigger a request. Full answers stream word by word over 2 to 4 seconds so you can start reading and speaking almost immediately. The app uses Server-Sent Events (SSE) so text arrives as it is generated rather than waiting for the full response.',
  },
  {
    category: 'Product',
    question: 'What question types does ZoomGuru handle?',
    answer: 'ZoomGuru automatically routes your question to the best model: behavioral questions (STAR method), technical definitions, coding problems (with approach, code, and complexity), system design questions (requirements, architecture, bottlenecks), and math problems (step-by-step working). Screenshot mode can read code on your screen, LeetCode problems, math equations, and diagrams.',
  },
  {
    category: 'Product',
    question: 'Does it work offline?',
    answer: 'ZoomGuru requires an internet connection for AI responses. Answers are generated by DeepSeek models running on our servers. However, local wake word detection and speech transcription via the Whisper tiny model run entirely on your device and work without internet.',
  },
  {
    category: 'Product',
    question: 'What operating systems does it support?',
    answer: 'ZoomGuru works on Windows 10/11 (64-bit) and macOS 12 Monterey or later (Intel and Apple Silicon). Screen share protection requires Windows 10 version 2004 or later. A Linux version is not currently planned.',
  },
  // Plans & Billing
  {
    category: 'Plans & Billing',
    question: 'What do I get on the free plan?',
    answer: 'The free plan gives you 3 complete interview sessions with up to 10 AI responses per session — no credit card required. You get the full AI engine, voice listening, answer streaming, and CV personalisation. Screenshot mode and the wake word ("Hey ZoomGuru") are Pro-only features.',
  },
  {
    category: 'Plans & Billing',
    question: 'What is the difference between Monthly and Lifetime?',
    answer: 'The Monthly plan (₦15,000) gives you full Pro access for 30 days. It does not auto-renew — you pay again when you want to continue. The Lifetime plan (₦100,000) is a one-time payment that never expires. Both plans are device-locked to one machine.',
  },
  {
    category: 'Plans & Billing',
    question: 'How do I pay?',
    answer: 'Payments are processed by Paystack and support card payments, bank transfers, and USSD. All prices are in Nigerian Naira (NGN). Paystack\'s checkout is secure and PCI-DSS compliant. Your card details are never stored by ZoomGuru.',
  },
  {
    category: 'Plans & Billing',
    question: 'Can I get a refund?',
    answer: 'No. All sales are final. Due to the instant digital delivery of your license, we do not offer refunds under any circumstances. We strongly recommend using the free tier to test ZoomGuru on your device before purchasing. If you believe there was a billing error (e.g. charged twice), contact support@zoomguru.com within 7 days with your payment reference.',
  },
  // Device & Licensing
  {
    category: 'Device & Licensing',
    question: 'Can I use ZoomGuru on multiple devices?',
    answer: 'Each license is locked to one machine using a SHA-256 hardware fingerprint generated from your CPU, RAM, MAC address, and other identifiers. One license equals one machine. If you get a new device and need to transfer your license, contact support@zoomguru.com — we allow one transfer every 90 days.',
  },
  {
    category: 'Device & Licensing',
    question: 'What happens when my Monthly plan expires?',
    answer: 'Your account automatically downgrades to the free tier the next time you log in. Your session history and CV profile are preserved. You can renew at any time by purchasing a new Monthly plan.',
  },
  {
    category: 'Device & Licensing',
    question: 'My license was not activated after payment. What do I do?',
    answer: 'License activation happens via Paystack\'s webhook, usually within seconds of payment. If it has not activated after 2 minutes, try logging out and back in — the app checks your license status on every login. If the issue persists, contact support@zoomguru.com with your Paystack payment reference.',
  },
  // Privacy & Security
  {
    category: 'Privacy & Security',
    question: 'Is my CV data safe?',
    answer: 'Your CV text is transmitted over HTTPS and stored encrypted in our database, used only to personalise your AI responses. We never sell, share, or use your CV for any other purpose. You can delete your CV and all account data at any time from Settings inside the app. Audio is processed locally on your device and is never sent to our servers.',
  },
  {
    category: 'Privacy & Security',
    question: 'Does ZoomGuru record my audio?',
    answer: 'No. Speech-to-text transcription runs entirely on your device using a local Whisper model. Audio is never transmitted to our servers or any third party. Only the final text transcript is sent to our backend for AI processing.',
  },
  {
    category: 'Privacy & Security',
    question: 'Does ZoomGuru store my screenshots?',
    answer: 'No. Screenshots are processed in memory, sent to our AI backend over an encrypted connection for analysis, and immediately discarded. We do not store, log, or retain any screenshots.',
  },
  // Referrals
  {
    category: 'Referrals',
    question: 'How does the referral programme work?',
    answer: 'Every ZoomGuru account gets a unique referral link. When someone signs up and purchases a plan using your link, you earn 25% of their payment as commission. Commissions accumulate in your referral balance and can be withdrawn once you reach ₦1,000 minimum. Payouts are processed manually within 2-3 business days.',
  },
];

const categories = ['All', ...Array.from(new Set(faqs.map(f => f.category)))];

function FAQItem({ faq, isOpen, onToggle }: { faq: (typeof faqs)[0]; isOpen: boolean; onToggle: () => void }) {
  return (
    <div
      className="rounded-2xl overflow-hidden transition-all duration-200"
      style={{
        background: isOpen ? 'rgba(255,255,255,0.07)' : 'rgba(255,255,255,0.03)',
        border: `1px solid ${isOpen ? 'rgba(255,255,255,0.15)' : 'rgba(255,255,255,0.07)'}`,
      }}
    >
      <button onClick={onToggle} className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left">
        <span className={`font-semibold text-sm leading-snug ${isOpen ? 'text-white' : 'text-white/70'}`}>
          {faq.question}
        </span>
        <span
          className={`flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center transition-all duration-200 ${isOpen ? 'bg-white text-black rotate-45' : 'text-white/50'}`}
          style={isOpen ? {} : { border: '1px solid rgba(255,255,255,0.15)' }}
        >
          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
          </svg>
        </span>
      </button>
      {isOpen && (
        <div className="px-6 pb-5">
          <p className="text-white/65 text-sm leading-relaxed font-light">{faq.answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [activeCategory, setActiveCategory] = useState('All');

  const filtered = activeCategory === 'All' ? faqs : faqs.filter(f => f.category === activeCategory);

  return (
    <section id="faq" className="py-28 px-4 relative overflow-hidden">
      <div className="max-w-3xl mx-auto relative z-10">

        <div className="text-center mb-14">
          <p className="text-white/65 text-xs font-bold uppercase tracking-[0.2em] mb-4">FAQ</p>
          <h2 className="text-4xl sm:text-5xl font-black text-white mb-5 tracking-tight">Common questions</h2>
          <p className="text-white/65 text-lg font-light">
            Anything else?{' '}
            <a href="mailto:support@zoomguru.com" className="text-white/80 hover:text-white transition-colors underline underline-offset-2">
              Email us
            </a>
          </p>
        </div>

        {/* Category filter */}
        <div className="flex flex-wrap gap-2 justify-center mb-10">
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => { setActiveCategory(cat); setOpenIndex(null); }}
              className="px-4 py-1.5 rounded-full text-xs font-semibold transition-all duration-150"
              style={
                activeCategory === cat
                  ? { background: 'rgba(255,255,255,0.15)', color: '#fff', border: '1px solid rgba(255,255,255,0.25)' }
                  : { background: 'transparent', color: 'rgba(255,255,255,0.45)', border: '1px solid rgba(255,255,255,0.1)' }
              }
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="space-y-3">
          {filtered.map((faq, i) => (
            <FAQItem
              key={i}
              faq={faq}
              isOpen={openIndex === i}
              onToggle={() => setOpenIndex(openIndex === i ? null : i)}
            />
          ))}
        </div>

        <div
          className="mt-14 text-center rounded-2xl p-10"
          style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)' }}
        >
          <h3 className="text-white font-black text-2xl mb-3 tracking-tight">
            Ready to ace your next interview?
          </h3>
          <p className="text-white/65 text-sm mb-8 font-light">
            Start free with no card required. 3 full sessions to see if ZoomGuru changes the game for you.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a href="/pricing" className="btn-shimmer font-bold py-3.5 px-8 rounded-xl transition-all duration-200 hover:scale-[1.02]">
              Start free
            </a>
            <a
              href="/download"
              className="text-white/65 hover:text-white font-semibold py-3.5 px-8 rounded-xl transition-all duration-200 inline-flex items-center justify-center gap-2"
              style={{ border: '1px solid rgba(255,255,255,0.12)' }}
            >
              Download now
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
