import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms and Conditions — ZoomGuru',
  description: 'Terms and conditions for using ZoomGuru.',
};

const LAST_UPDATED = 'May 19, 2025';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-24">
      <div className="mb-12">
        <p className="text-xs font-bold uppercase tracking-[0.15em] text-white/40 mb-3">Legal</p>
        <h1 className="text-4xl font-black text-white tracking-tight mb-4">Terms and Conditions</h1>
        <p className="text-white/50 text-sm">Last updated: {LAST_UPDATED}</p>
      </div>

      <div className="space-y-10 text-white/70 text-sm leading-relaxed">

        <section>
          <h2 className="text-white font-bold text-lg mb-3">1. Acceptance of Terms</h2>
          <p>
            By downloading, installing, or using ZoomGuru ("the App", "the Service"), you agree to be bound by these
            Terms and Conditions. If you do not agree to these terms, do not use the Service.
          </p>
          <p className="mt-3">
            These terms apply to all users of ZoomGuru, including free-tier and paid subscribers.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">2. Description of Service</h2>
          <p>
            ZoomGuru is an AI-powered desktop application designed to assist users during job interviews. It operates
            as a transparent, always-on-top overlay that is excluded from screen capture software using operating
            system-level APIs. The App listens to interview audio, captures screenshots on demand, and generates
            AI-powered responses based on the user's uploaded CV.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">3. User Responsibilities</h2>
          <p>You are solely responsible for how you use ZoomGuru. By using the Service you agree that:</p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>You will comply with the rules, policies, and codes of conduct of any employer, recruiting agency, or platform you interact with during your interviews.</li>
            <li>You understand that the use of AI assistance during interviews may be prohibited by certain employers or platforms.</li>
            <li>You will not use ZoomGuru to deceive, defraud, or misrepresent your qualifications or identity.</li>
            <li>You accept full personal liability for any consequences arising from your use of the App during an interview process.</li>
            <li>You will not reverse engineer, decompile, or attempt to extract the source code of the App.</li>
            <li>You will not use the App for any unlawful purpose.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">4. Account and Device Locking</h2>
          <p>
            Each paid license is bound to a single device using a hardware fingerprint. You may not transfer, resell,
            or share your license with any other person or device. ZoomGuru reserves the right to deactivate licenses
            used in violation of this policy without refund.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">5. Payments and Subscriptions</h2>
          <p>
            Payments are processed securely via Paystack. All prices are in Nigerian Naira (NGN). Monthly licenses
            grant access for 30 days from the date of purchase and must be renewed manually. Lifetime licenses grant
            perpetual access with no recurring charge.
          </p>
          <p className="mt-3">
            Please read our <Link href="/refund-policy" className="text-white underline underline-offset-2 hover:text-white/80">Refund Policy</Link> before
            completing a purchase.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">6. AI-Generated Content</h2>
          <p>
            Responses generated by ZoomGuru are produced by third-party AI models (DeepSeek). ZoomGuru does not
            guarantee the accuracy, completeness, or suitability of any AI-generated answer. You should always review
            and verify AI responses before relying on them. ZoomGuru accepts no liability for decisions made based on
            AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">7. Intellectual Property</h2>
          <p>
            All intellectual property in the ZoomGuru application, website, and associated materials is owned by or
            licensed to ZoomGuru. You are granted a limited, non-exclusive, non-transferable license to use the App
            for personal, non-commercial purposes in accordance with these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">8. Disclaimer of Warranties</h2>
          <p>
            ZoomGuru is provided "as is" without warranties of any kind, express or implied. We do not warrant that
            the App will be uninterrupted, error-free, or that screen share exclusion will work on all systems,
            versions, or configurations of screen capture software.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, ZoomGuru and its owners shall not be liable for any
            indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of
            employment opportunity, revenue, or data, arising from your use of or inability to use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">10. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to ZoomGuru at any time, with or without notice,
            for violation of these Terms or for any other reason at our sole discretion.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">11. Changes to Terms</h2>
          <p>
            We may update these Terms at any time. Continued use of the Service after changes are posted constitutes
            your acceptance of the revised Terms. We encourage you to review this page periodically.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">12. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved
            in the courts of Nigeria.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-lg mb-3">13. Contact</h2>
          <p>
            For questions about these Terms, contact us at{' '}
            <a href="mailto:support@zoomguru.xyz" className="text-white underline underline-offset-2 hover:text-white/80">
              support@zoomguru.xyz
            </a>.
          </p>
        </section>
      </div>

      <div className="mt-16 pt-8 border-t border-white/10 flex flex-wrap gap-6 text-xs text-white/40">
        <Link href="/privacy" className="hover:text-white/70 transition-colors">Privacy Policy</Link>
        <Link href="/refund-policy" className="hover:text-white/70 transition-colors">Refund Policy</Link>
        <Link href="/faq" className="hover:text-white/70 transition-colors">FAQ</Link>
      </div>
    </div>
  );
}
